version: '3.8'

services:
  api:
    image: registry.digitalocean.com/proza1k/belover-node:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./node_modules:/usr/src/app/node_modules
    network_mode: host