on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

name: build and deploy
jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Docker - build
        run: docker build . -t ${{ secrets.DOCKERHUB_NODE_TAG }}

      - name: Docker - Push
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ secrets.DOCKERHUB_NODE_TAG }}